[project]
name = "reaction-speed-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "keyboard>=0.13.5",
    "mss>=10.1.0",
    "numpy>=2.3.4",
    "pillow>=12.0.0",
    "pyautogui>=0.9.54",
]
